### ISSUE TITLE
OIncorrect address

### ISSUE THREAD

**Issue by andrzejtp** [JeffyCN/rockchip_mirrors#10]
https://github.com/JeffyCN/rockchip_mirrors/blob/965c07ae8c1b4171a73e135ff0734c790c9dfbcc/package/pcre/pcre.mk#L8

The url in the .mk refers to a non-existent address.

**Comment by JeffyCN** [comment]
done:https://github.com/JeffyCN/rockchip_mirrors/commit/b80407370bab89dee513bf78b96e12c853b0f50b

thanks :)
