### ISSUE TITLE
vcodec_service: vcodec_service_cmd_send ioctl VPU_IOC_SET_REG failed ret -1 errno 14 Bad address

### ISSUE THREAD

**Issue by LianYangCn** [JeffyCN/rockchip_mirrors#14]
mpp:  https://github.com/JeffyCN/rockchip_mirrors/tree/mpp
gstreamer-rockchip: https://github.com/JeffyCN/rockchip_mirrors/tree/gstreamer-rockchip
kernel: 
merge https://github.com/JeffyCN/rockchip_mirrors/blob/kernel/drivers/video/rockchip/vcodec to https://github.com/friendlyarm/kernel-rockchip/blob/kernel/drivers/video/rockchip/vcodec

GStreamer launch with error: 
```
vcodec_service: vcodec_service_cmd_send ioctl VPU_IOC_SET_REG failed ret -1 errno 14 Bad address
```

**Comment by JeffyCN** [comment]
sorry, i don't handle mpp issues. likely due to kernel version miss-matched somewhere.
