### ISSUE TITLE
RGA problem with RGBtoYUV converstion

### ISSUE THREAD

**Issue by kadirbeytorun** [JeffyCN/rockchip_mirrors#17]
Hello @JeffyCN ,

As mentioned in title, we are converting a grayscale RGB frame to YUV frame using RGA library. Both RGA lib and RGA kernel driver are from same SDK version.
This is what we get as resulting frame after conversion using methods shown in linux-rga's samples/legacy :
![Selection_034](https://user-images.githubusercontent.com/49143235/176842183-3acc4ca8-ee50-4a58-a95f-a37b8f3e6800.png)
Obviously the frame got messed up and the issues is same as the one mentioned in RGA_FAQ.md/Q2.11. 

When we convert RGB frame to YUV using " https://github.com/Jerzha/samples-toybrick-rga ", the frame is correctly converted:
![Selection_035](https://user-images.githubusercontent.com/49143235/176842974-47c40983-d025-40db-bc90-43baab3d9350.png)
Conversion is correct, however the library Jerzha shared is not updated anymore and it makes more sense to use linux-rga library's methods, to be able to add more functionality to our projects. Also this library seems to communicate with rga library using "ioctl" commands, which is very confusing and there is no documentation about how it works.

What went wrong here? What would you suggest to solve this?

Thanks in advance.

**Comment by JeffyCN** [comment]
hi, please note this is just a mirror repo...

i'm not the rga maintainer ;)

for this kind of issues, please find the maintainer or recent commitors and mail them. or use rockchip's redmine issue system
