### ISSUE TITLE
Update boot_merger and trust_merger sources

### ISSUE THREAD

**Issue by Googulator** [JeffyCN/rockchip_mirrors#22]
The boot_merger and trust_merger source code in this repo is significantly older than the binaries, and doesn't support RK35xx. This makes self-hosted builds for these platforms impossible, requiring cross-compilation on an x86 machine instead.

This is a follow-up to #4.

**Comment by JeffyCN** [comment]
sorry, i don't have that.

it looks like someone re-wrote it with python, you can try to mail the committer for source code.

**Comment by Googulator** [comment]
You mean chenjh?

The "new" boot/trust_merger binaries don't appear to be compiled Python.
