### ISSUE TITLE
Failed to initialize MPP context?

### ISSUE THREAD

**Issue by danergo** [JeffyCN/rockchip_mirrors#25]
I compiled these repos: librga (from rockchip_mirrors), mpp (this repo), ffmpeg-rk on a NanoPI R5C locally.
Then I also did "sudo make install" for all projects.

Now, when I try running this ffmpeg I got:

```
[hevc_rkmpp @ 0x55a919c7e0] Failed to initialize MPP context (code = -1).
[hevc_rkmpp @ 0x55a919c7e0] Failed to initialize RKMPP decoder.                                                       

```
Can you help me understand which point is missing?

**Comment by JeffyCN** [comment]
i don't use ffmpeg much, i would prefer gstreamer.

for ffmpeg, maybe you can check:
https://github.com/JeffyCN/FFmpeg/issues/18

**Comment by danergo** [comment]
I wish to use Emby (it's a media server), which relies on FFMPEG, so unfortunately I don't have other choice.

Will try yours, and let you know. Thank you very much!

**Comment by danergo** [comment]
My mpp might be wrong, can you please point me to the correct mpp repo which I need to build?

**Comment by JeffyCN** [comment]
the mpp should match the kernel driver, so i don't know which version you need...

the mpp maintainer's repo:
https://github.com/HermanChen/mpp

**Comment by amazingfate** [comment]
You can check mpp logs from syslog by `journalctl -f`.
I encountered this issue when runnning as root on armbian because armbian has a kernel which has enabled `CONFIG_ION=y` and then mpp will try to use `/dev/ion` because the process just have the permission to access it. Running as normal user can avoid it.

**Comment by jjm2473** [comment]
On rk3568 , `/dev/ion` can break MPP, just delete it, or disable it on kernel config.

DMA_HEAP has better performance than ION, it's a perfer solution. If DMA_HEAP not supported on your kernel (like 4.19), use DRM instead.

**Comment by danergo** [comment]
If I remove /Dev/ion, it works. Thank you.
