### ISSUE TITLE
gstreamer-rkisp plugin doesn't buid

### ISSUE THREAD

**Issue by firexx** [JeffyCN/rockchip_mirrors#3]
Hi Jeffy,
to get access to ov13850 is gst plugin necessary. in some documentation like hier: http://opensource.rock-chips.com/wiki_Rockchip-isp1 it is named  as "rkcamsrc" on others it is named as "rkisp". But no one of them was build from meta-rockchip\recipes-multimedia\gstreamer-rockchip.

**Comment by JeffyCN** [comment]
Hi,

the wiki is out-dated(the rockchip guys don't actually update it for years).
the newest documents are maintained in the doc repo, here's the mirror:
https://github.com/JeffyCN/rockchip_mirrors/tree/docs

in a word, the rockchip gst isp plugins are no longer needed. in newer sdk, there should be a remote 3A service come from:
https://github.com/JeffyCN/meta-rockchip/blob/master/recipes-multimedia/rockchip-rkisp/rockchip-rkisp.bb
https://github.com/JeffyCN/rockchip_mirrors/tree/camera_engine_rkisp

with this daemon, you can use the official v4l2src to access isp camera.
