### ISSUE TITLE
[gstreamer-rockchip]Rendering on Android consume a lot of CPU

### ISSUE THREAD

**Issue by Meonardo** [JeffyCN/rockchip_mirrors#38]
Env: 
- Kernel info: Linux localhost 5.10.66 #394 SMP PREEMPT Fri Jul 7 13:30:47 CST 2023 aarch64;
- GStreamer v1.22.6;
- gstreamer-rockchip [latest code](https://github.com/JeffyCN/rockchip_mirrors/commit/aab4a4210b1e8cf1f8fa26f335f93110c39b4dbc);
- single H.264 RTSP video stream(1920x1080@25fps)

---
GStreamer pipelines:
1. without renderer, works great low CPU usage, very fast at decoding.
  ```
  rtspsrc location=%s ! rtph264depay ! h264parse ! mppvideodec ! fakesink
  ```
![image](https://github.com/JeffyCN/rockchip_mirrors/assets/13954438/80e64fe8-ed92-4f7e-8a6b-a007e0b3f3a0)

2. with renderer(`glimagesink`), the CPU up to `105%`
 ```
  rtspsrc location=%s ! rtph264depay ! h264parse ! mppvideodec ! glimagesink
 ```
![image](https://github.com/JeffyCN/rockchip_mirrors/assets/13954438/8fecabb0-e994-45e6-9e0b-0f4cc347f4a4)

---
I am using `SurfaceView` as renderer on Android, in native I got the `ANativeWindow` from `ANativeWindow_fromSurface(env, surface)`, then I use `gst_video_overlay_set_window_handle(GST_VIDEO_OVERLAY(video_sink), (guintptr)window)` pass to GStreamer.
Did I miss something? Do I need apply some patches in GStreamer? @JeffyCN sorry to bother you, could you give me some advice? thanks.

**Comment by ScorpiosCrux** [comment]
I have the same issue by the way. Even on an RK3588, decoding anything higher than 1080p 60FPS, causes the CPU to go extremely high.

**Comment by JeffyCN** [comment]
for glimagesink, it will try to import buffer to texture, which is normally a neon version of memcpy.

check the gl related hack patches under:
https://github.com/JeffyCN/rockchip_mirrors/tree/buildroot/package/gstreamer1/gst1-plugins-base

for dmabuf direct importing

**Comment by Meonardo** [comment]
After applied the patch [1](https://github.com/JeffyCN/rockchip_mirrors/blob/buildroot/package/gstreamer1/gst1-plugins-base/0010-glupload-dmabuf-prefer-DirectDmabufExternal-uploader.patch) and patch [2](https://github.com/JeffyCN/rockchip_mirrors/blob/buildroot/package/gstreamer1/gst1-plugins-base/0009-HACK-gl-egl-allow-direct-dmabuf-import-when-unable-t.patch) to GStreamer, I have managed to low the CPU usage down to `40%` for a single H.264 RTSP video(1920x1080@25fps) decoding & rendering, does it look normal to you on an rk3588? @JeffyCN, thank you for your reply!

**Comment by JeffyCN** [comment]
i haven't use android with this before, you can try to check the cpu usage of threads, the decoder and renderer should not cause much with these patches.
