### ISSUE TITLE
How do I check if the plugin is RGA enabled?

### ISSUE THREAD

**Issue by huntlin** [JeffyCN/rockchip_mirrors#43]
gstreamer:1.18.5, The system is Ubuntu，I found through the debug, LD library that gstreamer does have librga introduced, but when I use the videoconvert component, there is no trace of enablement, and I tried export GST_VIDEO_CONVERT_USE_RGA=1 not even printing rga_api version. How can I check if the plugin is RGA enabled?

**Comment by huntlin** [comment]
i tried export GST_DEBUG=6，i find log is "rga does no match media" what is that mean and How do I fix this?

**Comment by JeffyCN** [comment]
i don't think i've ported my custom gst rga patch to ubuntu platform(it should not be easy though), and my patch doesn't contain such message(rga does no match media).

my patch is simple, if you were porting it, maybe try to add logs to debug:
https://github.com/JeffyCN/rockchip_mirrors/blob/buildroot/package/gstreamer1/gst1-plugins-base/0008-video-converter-Support-rockchip-RGA-2D-accel.patch

**Comment by huntlin** [comment]
hi，I saw the log output of RGA enabled through debug, but it still doesn't print rga_api version still doesn't seem to call rga, how do I troubleshoot this?
![image](https://github.com/JeffyCN/rockchip_mirrors/assets/61825325/bd44442a-4ab1-4aef-a931-dddd3ade88e5)

**Comment by JeffyCN** [comment]
that log means rga is enabled, but it would be called only when needed.

for example you can set width/height property of mppvideodec

**Comment by huntlin** [comment]
gst-launch-1.0 v4l2src device=/dev/video9  !  video/x-raw,width=640,height=480! videoconvert ! video/x-raw,format=NV12 !  mpph264enc ! h264parse ! rtph264pay ! udpsink host=xxx port=1234  like this?

**Comment by JeffyCN** [comment]
try something like '! mpph264enc width=1024 height=1024 !'

**Comment by huntlin** [comment]
Still won't work
```
GST_DEBUG=2 gst-launch-1.0 v4l2src device=/dev/video9  !  video/x-raw,width=640,height=480! videoconvert ! video/x-raw,width=640,height=480,format=NV12 !  mpph264enc width=640 height=480 ! h264parse ! rtph264pay ! udpsink host=192.168.1.175 port=1234

0:00:00.696048401  2488   0x5584fa44f0 WARN                     mpp gstmpp.c:122:gst_mpp_use_rga: RGA enabled 
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
0:00:02.667704098  2488   0x5584ef6b60 WARN                 v4l2src gstv4l2src.c:978:gst_v4l2src_create:<v4l2src0> lost frames detected: count = 1 - ts: 0:00:01.884865323
0:00:06.393084591  2488   0x5584ef6b60 WARN                 v4l2src gstv4l2src.c:978:gst_v4l2src_create:<v4l2src0> lost frames detected: count = 1 - ts: 0:00:05.612881281
0:00:08.004639111  2488   0x5584ef6b60 WARN                 v4l2src gstv4l2src.c:978:gst_v4l2src_create:<v4l2src0> lost frames detected: count = 1 - ts: 0:00:07.224814031
0:00:08.776754190  2488   0x5584ef6b60 WARN                 v4l2src gstv4l2src.c:978:gst_v4l2src_create:<v4l2src0> lost frames detected: count = 1 - ts: 0:00:07.996895281
```

**Comment by JeffyCN** [comment]
please remove the videoconvert. (it would be called only when needed)

**Comment by huntlin** [comment]
if i want set videocovnert to change format BGR,how can i set ?

**Comment by huntlin** [comment]
> 尝试类似'！mpph264enc 宽度=1024 高度=1024 ！'

I tested it successfully， if i want set videocovnert to change format BGR,how can i set ?

**Comment by huntlin** [comment]
like `videoconvert ! video/x-raw format=BGR !` but rga not working

**Comment by JeffyCN** [comment]
there's also a format property in mpp*enc

**Comment by huntlin** [comment]
Does mppvideodec also have the same function?

**Comment by JeffyCN** [comment]
yes, you can check supported properties by gst-inspect-1.0 <plugin>
