### ISSUE TITLE
Bug in the alpha decoder

### ISSUE THREAD

**Issue by ndufresne** [JeffyCN/rockchip_mirrors#45]
Hi, sorry to bother you, but we fixed a bug in upstream gstreamer that has been introduce in your gstreamer-rockchip repo too. You'll find the details here: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/6452

In short, we don't cast the value pass as vararg to "max-size-time" property, meaning we pass 32bit instead of 64.

**Comment by JeffyCN** [comment]
Hi, thanks for noticing, i've ported that patch.
