### ISSUE TITLE
no mpp265enc after install gstreamer-rockchip

### ISSUE THREAD

**Issue by andrescera** [JeffyCN/rockchip_mirrors#53]
I´d like to ask if there are any other requirements to get those plugins working, I compiled and installed mpp and GStreamer (1.14)  and then built the packages using:

`meson build -Dprefix=/usr/local -Drockchipmpp=enabled -Drkximage=enabled -Dkmssrc=enabled -Drga=enabled Dvpxalphadec=enabled`
`cd build`
`ninja`
`sudo ninja install`

but after running

`gst-inspect-1.0 | grep mpp`
The output I get is:

 rockchipmpp:  mppvideodec: Rockchip's MPP video decoder
rockchipmpp:  mppjpegdec: rockchip's MPP JPEG image decoder
typefindfunctions: audio/x-musepack: mpc, mpp, mp+

Is there any other parameter or requirement I should use to get things working properly?

**Comment by JeffyCN** [comment]
it depends on mpp, would not be registered if mpp failed to init

**Comment by andrescera** [comment]
thanks it was my kernel version I downgraded from 6.11 to 6.1 and it  worked well
