### ISSUE TITLE
Should GstMppDec be GstMppEnc in file gst/rockchipmpp/gstmppenc.h?

### ISSUE THREAD

**Issue by rw-vemotion** [JeffyCN/rockchip_mirrors#7]
I was looking through the code with a view to using MPP directly (without GStreamer) and just noticed
https://github.com/JeffyCN/rockchip_mirrors/blob/b88d30d93a9e22a68dd029807f4842360d28a680/gst/rockchipmpp/gstmppenc.h#L36
Which probably should be 
`typedef struct _GstMppEnc GstMppEnc;`

I'm not sure what the implications of this are but it looks wrong on first view

**Comment by JeffyCN** [comment]
hmm, thanx for noticing, well remove it soon.

and for mpp usage, there should be a few examples under it's tests/
